### PR TITLE
Fix evaluations request

### PR DESCRIPTION
**Pull request by andrwlt**
**Features:**
- [x] Add credibility to the identity
- [x] Combine resolver credibility and identity credibility
- [x] Increase or decrease the credibility of payment parties (payer, payee, and resolver)
- [x] Blacklisted resolver who terminated cause of low credibility

**Missing tests:**
- [x] Test `update_identity_data`
- [x] Test `increase_credibility` and `reduce_credibility`
- [x] Test chosen the random resolver

**Documentation:**
- [x] Add document for Events and Error enum

**Others: **
- [x] Fix `cargo clippy`

### CODE REVIEW

**Comment by andrwlt** [comment]
@antdo All done! Please have a look 🙏

**Review by antdo — COMMENTED** [review]
LGTM, thanks @psyduckio

**Review by antdo — COMMENTED** [review]
Good to merge now, Thanks @psyduckio

**Review by antdo — APPROVED** [review]
LGTM

**Pull request merged**
